export const ENV = {
  COINGECKO_API_KEY: process.env.NEXT_PUBLIC_COINGECKO_API_KEY || "",
  COINGECKO_BASE_URL: process.env.NEXT_PUBLIC_COINGECKO_API_URL || "",
  WALLETCONNECT_PROJECT_ID:
    process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID || "",
  NEXT_PUBLIC_WALLETCONNECT_APP_NAME:
    process.env.NEXT_PUBLIC_WALLETCONNECT_APP_NAME || "",
} as const;
